version: "3.8"
services:
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - "443:443"
    depends_on:
      nginx-proxy-manager:
        condition: service_healthy
