version: "3.8"
services:
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - "443:443"
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
